Popup window
Kasaija-Kenneth/mobile_first_portfolio pull request #11
Opened 2022-09-15 17:53 UTC by ReemMohamedAbdelfatah

Added popup menu for mobile and desktop versions.

2022-09-15 18:05 UTC, jasonfelice approved these changes
Hi @Kasaija-Kenneth, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<p align="center"><img  src="https://media2.giphy.com/media/Zcm5DaspYzhTxstkF4/giphy.gif?cid=ecf05e472vkr75z01b5qlseyap0ylpyn6krdcf0fokyey0cx&rid=giphy.gif&ct=g"/></p>

## Highlights
No Linter errors✔️
GitHub flow followed✔️
Great design✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-15 18:12 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi Team👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media0.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights:  
* All tests passed ✔️ 
* Project cards are created dynamically ✔️

## Required Changes:
_Please check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-15 18:12 UTC, ha-manel commented on index.html
> +              </ul> -->
- [ ] Kindly remove this commented code to improve readability and make your code more professional 💯

2022-09-15 18:12 UTC, ha-manel commented on index.html
> +              <h2 class="deskHeading"></h2>
- [ ] Kindly try to make the design look as much as possible like it is in Figma. the placement of the modal elements is different, and the size of the image is different too.

## Your design:
![image](https://user-images.githubusercontent.com/50721479/190477994-cd9ccc1a-82c6-4d49-8548-3dacdc1bc45f.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/190478066-8f9ee959-23eb-47df-b0c5-52ec6e908a8b.png)

2022-09-15 18:12 UTC, ha-manel commented on index.html
> +                <div>
- [ ]  Kindly try to make the mobile design look as much as possible like it is in Figma. the placement of the modal elements is different here too and the technologies badges look very different from the ones in Figma ✍️ 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/190478526-0cf4b29f-d0a1-46cb-b603-e7995b5d0efc.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/190478598-9407994f-08ac-4c4c-860f-2c03e408149e.png)

2022-09-16 01:40 UTC, mateo951 approved these changes
### Hi Team, 

Well done making the requested changes by the previous reviewer ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🐐 
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 07:29 UTC, merged